stages:
  - build
  - push

build:
  stage: build
  script:
    - docker-compose build google
  only:
    - master@gpii-ops/exekube

push:
  stage: push
  script:
    - docker push gpii/exekube:0.4.0-google
  only:
    - master@gpii-ops/exekube
