stages:
  - build
  - push

build-master:
  stage: build
  script:
    - make build
  only:
    refs:
      - master

push-master:
  stage: push
  script:
    - make push
  only:
    - tags

build-tag:
  stage: build
  script:
    - make build-tag
  only:
    - tags

push-tag:
  stage: push
  script:
    - make push-tag
  only:
    - tags
