version: "3"

services:
  google:
    image: exekube/exekube:0.3.0-google
    build:
      context: .
      dockerfile: dockerfiles/google/Dockerfile
  alicloud:
    image: exekube/exekube:0.3.0-alicloud
    build:
      context: .
      dockerfile: dockerfiles/alicloud/Dockerfile
  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - .:/docs
    ports:
      - 8000:8000
    entrypoint: mkdocs
    command:
      - serve
      - --livereload
      - --dev-addr=0.0.0.0:8000
