version: "3.5"

services:
  exekube:
    build: ./_docker
    working_dir: /exekube
    environment:
      VAULT_ADDR: https://localhost
      VAULT_CACERT: /exekube/live/prod/kube/core/vault/release/secrets/vault-tls/ca.crt
      GOOGLE_CREDENTIALS: /exekube/live/prod/owner-key.json
      TF_LOG:
      TF_INPUT: 0
      XK_LIVE_DIR:
      TF_VAR_gcp_project:
      TF_VAR_gcp_remote_state_bucket:
      TF_VAR_cloudflare_auth:
      TF_VAR_registry_auth:
      TF_VAR_chartrepo_auth:
    ports:
      - 8001:8001
    volumes:
      - .:/exekube
      - ./config/helm:/root/.helm
      - ./config/terragrunt:/root/.terragrunt
      - ./config/gcloud:/root/.config/gcloud
      - ./config/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"

  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - .:/docs
    ports:
      - 8000:8000
    entrypoint: mkdocs
    command:
      - serve
      - --livereload
      - --dev-addr=0.0.0.0:8000
