site_name: Exekube Docs
repo_name: exekube/exekube
repo_url: https://github.com/exekube/exekube
edit_uri: https://github.com/exekube/exekube/pulls

pages:
  - Overview: index.md
  - Introduction:
      - What is Exekube?: introduction/what-is-exekube.md
      - Exekube in comparison: introduction/exekube-vs-other.md
      - Exekube's Architecture: introduction/architecture.md
  - In Practice:
      - 'Get started with Exekube': in-practice/getting-started.md
      - 'Configure production-grade networking': in-practice/production-networking.md
      - 'Configure production-grade storage': in-practice/production-storage.md
  - Miscellaneous:
      - 'Terraform / Terragrunt module hierarchy in Exekube projects': misc/module-hierarchy.md

copyright: 'Copyright &copy; 2018 Ilya Sotkov'

docs_dir: 'docs'
extra_css:
  - 'theme/extra.css'
extra_javascript:
  - 'theme/assets/javascripts/application.js'
markdown_extensions:
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: docs/theme
  feature:
    tabs: true
  font:
    text: Fira Sans
    code: Roboto Mono
  palette:
    primary: indigo
    accent: indigo
