site_name: Exekube Docs
repo_name: exekube/exekube
repo_url: https://github.com/exekube/exekube
edit_uri: ""

pages:
  - Overview: index.md
  - Introduction:
      - 'What is Exekube?': introduction/what-is-exekube.md
      - 'Exekube in comparison': introduction/exekube-vs-other.md
  - Setup and Installation:
      - 'On Google Cloud Platform': setup/gcp-gke.md
      - 'On Amazon Web Services': setup/aws-eks.md
  - Usage:
      - 'Deploy an application': usage/deploy-app.md
      - 'Guide to Exekube directory structure and framework usage': usage/directory-structure.md
  - Miscellaneous:
      - 'Compare using Helm CLI and terraform-provider-helm': misc/helm-cli-vs-terraform-provider-helm.md
      - 'Configure a Helm release': misc/configure-helm-release.md
      - 'Use HashiCorp Vault to manage secrets': misc/vault-integration.md
      - 'Project feature tracker': misc/feature-tracker.md
      - 'Managing secrets in Exekube': misc/secrets.md
      - 'Add audit config for KMS and secret store bucket': misc/add-audit-config.md
      - 'API Design': misc/api-design.md
      - 'Security features': misc/security.md
  - Reference:
      - 'gke-cluster module': reference/gke-cluster.md
      - 'helm-release module': reference/helm-release.md

copyright: 'Copyright &copy; 2018 Ilya Sotkov'

docs_dir: 'docs'
extra_css:
  - 'css/extra.css'
extra_javascript:
  - 'theme/assets/javascripts/application.js'
markdown_extensions:
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: docs/theme
  feature:
    tabs: true
  font:
    text: Fira Sans
    code: Roboto Mono
  palette:
    primary: indigo
    accent: indigo
