version: 2
jobs:
  apply-live:
    working_directory: /exekube
    environment:
      XK_LIVE_DIR: /exekube/live/prod
      TF_INPUT: 0
      TF_LOG:
      TF_VAR_gcp_project: production-project-193513
      TF_VAR_gcp_remote_state_bucket: project-terraform-state
      VAULT_ADDR: https://localhost
      VAULT_CACERT:
    docker:
      - image: ilyasotkov/exekube:latest
    steps:
      - checkout
      - run:
          name: Give Terraform plan
          command: ./_docker/docker-entrypoint.sh plan
  deploy-docs:
    docker:
      - image: squidfunk/mkdocs-material:latest
    steps:
      - checkout
      - run: echo $CIRCLE_REPOSITORY_URL
      - run:
          name: Build and deploy website to GitHub Pages
          command: mkdocs gh-deploy --message "Deployed with MkDocs and CircleCI $CIRCLE_BUILD_URL [ci skip]"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docs
      - apply-live:
          context: org-global
