version: 2
jobs:
  apply-live:
    working_directory: /exekube
    environment:
      XK_LIVE_DIR: /exekube/live/prod
      TF_INPUT: "0"
      TF_LOG: ""
      TF_VAR_gcp_project: production-project-193513
      TF_VAR_gcp_remote_state_bucket: project-terraform-state
      VAULT_ADDR: https://localhost
      VAULT_CACERT:
    docker:
      - image: ilyasotkov/exekube:latest
    steps:
      - checkout
      - run:
          name: Authorize to gcloud
          command: |
              echo $GOOGLE_CREDENTIALS > google-credentials.json \
              && gcloud auth activate-service-account \
              --key-file=google-credentials.json \
              && rm -rf google-credentials.json \
              && mkdir -p /exekube/backup/tls \
              && echo '$KUBE_LE_TLS_CERTS' > /exekube/backup/tls/secret.json
      - run:
          name: Create everything
          command: ./_docker/docker-entrypoint.sh apply && echo Done!
      - run:
          name: Destroy everything
          command: ./_docker/docker-entrypoint.sh destroy && echo Done!
  deploy-docs:
    docker:
      - image: squidfunk/mkdocs-material:latest
    steps:
      - checkout
      - run: echo $CIRCLE_REPOSITORY_URL
      - run:
          name: Build and deploy website to GitHub Pages
          command: mkdocs gh-deploy --message "Deployed with MkDocs and CircleCI $CIRCLE_BUILD_URL [ci skip]"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docs
      - apply-live:
          context: org-global
