version: 2
jobs:
  deploy:
    docker:
      - image: squidfunk/mkdocs-material:latest
    steps:
      - checkout
      - run: echo $CIRCLE_REPOSITORY_URL
      - run:
          name: Build and deploy website to GitHub Pages
          command: mkdocs gh-deploy --message "[ci skip] Deployed with MkDocs"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
