version: 2
jobs:
  apply-live:
    working_directory: /exekube
    docker:
      - image: ilyasotkov/exekube:latest
    steps:
      - checkout
      - run:
          name: Test working directory
          command: echo $CIRCLE_WORKING_DIRECTORY && pwd && ls -alh
  deploy:
    docker:
      - image: squidfunk/mkdocs-material:latest
    steps:
      - checkout
      - run: echo $CIRCLE_REPOSITORY_URL
      - run:
          name: Build and deploy website to GitHub Pages
          command: mkdocs gh-deploy --message "[ci skip] Deployed with MkDocs"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
      - apply-live:
          context: org-global
