apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: ${tiller_namespace}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tiller
  namespace: ${tiller_namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: ${tiller_namespace}
