resources:
  - name: concourse
    type: git
    source:
      uri: https://github.com/concourse/concounse.git
      branch: master

jobs:
  - name: hello-world
    plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: '3.6'
          run:
            path: echo
            args: ["Hello from Concourseland!"]
