resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: exekube
  type: git
  source:
    uri: https://github.com/ilyasotkov/exekube.git
    branch: develop

- name: repo-master
  type: git
  source:
    uri: ((github_repo_uri))
    private_key: ((github_private_key))
    branch: master

- name: rc-version
  type: semver
  source:
    driver: git
    uri: ((github_repo_uri))
    private_key: ((github_private_key))
    branch: rc-version
    file: version
    intial_version: ((initial_version))

- name: docker-image
  type: docker-image
  source:
    repository: registry.swarm.pw:443/rails-react-boilerplate
    username: ((docker_registry_username))
    password: ((docker_registry_password))

- name: helm-release
  type: helm
  source:
    cluster_url: ((kube_url))
    cluster_ca: ((kube_ca))
    token: ((kube_token))
    repos:
    - name: private
      url: ((private_charts_repo_url))

jobs:
# master branch is used for staging, so we version it as x.y.z-rc.n
- name: version-master
  serial: true
  serial_groups: [ update-version ]
  plan:
  - aggregate:
    - get: master
      resource: repo-master
      trigger: true
    - get: rc-version
  - put: rc-version
    params:
      pre: rc

- name: build-master
  serial: true
  plan:
  - get: master
    resource: repo-master
    trigger: true
    passed: [ version-master ]
  - get: rc-version
    passed: [ version-master ]
  - put: docker-image
    params:
      build: master
      tag: rc-version/version
      cache: false
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: release-master
  serial: true
  plan:
  - get: exekube
  - get: repo-master
    trigger: true
    passed: [ build-master ]
  - get: rc-version
    passed: [ version-master ]
  - put: helm-release
    params:
      chart: private/rails-app
      values: exekube/.concourse/release/values.yaml
      release: exekube/.concourse/release/release.txt
      replace: true
      devel: true
      recreate_pods: false
      override_values:
      - key: image.pullSecret
        value: registry-dockercfg
      - key: image.tag
        path: rc-version/version
      - key: image.repository
        value: registry.swarm.pw/rails-react-boilerplate
