resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

resources:
- name: rails-react-boilerplate
  type: git
  source:
    uri: https://github.com/ilyasotkov/rails-react-boilerplate.git
    branch: master
- name: rails-react-boilerplate-image
  type: docker-image
  source:
    repository: registry.swarm.pw:443/rails-react-boilerplate
    username: ((docker_registry_username))
    password: ((docker_registry_password))
- name: helm-release
  type: helm
  source:
    cluster_url: ((kube_url))
    cluster_ca: ((kube_ca))
    token: ((kube_token))
    repos:
      - name: private
        url: ((private_charts_repo_url))

jobs:
- name: build and push rails-react-boilerplate docker image
  serial: true
  plan:
    - get: rails-react-boilerplate
      version: latest
      trigger: false
    - put: rails-react-boilerplate-image
      params:
        build: rails-react-boilerplate
        tag: rails-react-boilerplate/VERSION
    - name: release the application helm chart
      serial: true
      plan:
        - put: helm-release
          params:
            chart: private/rails-app-1.0.0.tgz
            values: exekube/.concourse/release/values.yaml
            release: exekube/.concourse/release/release.txt
            replace: true
            devel: true
            recreate_pods: true
            override_values:
            - hide: false
              key: image.tag
              value: '1.0.2'
