concourse:
  githubAuth:
    enabled: true
    user: ilyasotkov

web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      kubernetes.io/tls-acme: "true"
    hosts:
      - ${domain_name}
    tls:
      - secretName: ${domain_name}-tls
        hosts:
          - ${domain_name}

rbac:
  create: false

secrets:
  create: false
