Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "2.101-alpine"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: ilyasotkov
  Cpu: "200m"
  Memory: "256Mi"
  ServicePort: 8080
  ServiceType: ClusterIP
  ServiceAnnotations: {}
  HostName: ${domain_name}
  ContainerPort: 8080
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
  InstallPlugins:
    - kubernetes:1.1.2
    - workflow-aggregator:2.5
    - workflow-job:2.16
    - credentials-binding:1.13
    - git:3.6.4
    - blueocean:1.3.5
  InitScripts:
  CustomConfigMap: false
  NodeSelector: {}
  Tolerations: {}
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    TLS:
      - secretName: jenkins-tls
        hosts:
          - ${domain_name}
Agent:
  Enabled: true
  Image: jenkins/jnlp-slave
  ImageTag: 3.10-1
  Component: "jenkins-slave"
  Privileged: false
  Cpu: "200m"
  Memory: "256Mi"
  AlwaysPullImage: false
  volumes:
  NodeSelector: {}
Persistence:
  Enabled: true
  Annotations: {}
  AccessMode: ReadWriteOnce
  Size: 8Gi
  volumes:
  mounts:
NetworkPolicy:
  Enabled: false
  ApiVersion: extensions/v1beta1
rbac:
  install: false
  serviceAccountName: default
  apiVersion: v1beta1
  roleRef: cluster-admin
