server:
  githubAuth:
    enabled: true
    openRegistration: false
    orgs: ""
    admin: "ilyasotkov"

persistence:
  enabled: true

secrets:
  create: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  hosts:
    - ${domain_name}
  tls:
    - secretName: ${domain_name}-tls
      hosts:
        - ${domain_name}
